### ISSUE TITLE
Incorrect Seller Central Domain for Saudi Arabia Marketplace

### ISSUE THREAD

**Issue by sw-engineer-a** [bizon/amazon-ids#343]
The marketplace for Saudi Arabia is currently configured to return the incorrect Seller Central domain. It is showing sellercentral.amazon.com.sa instead of the correct domain, which should be sellercentral.amazon.sa as specified in  https://developer-docs.amazon.com/sp-api/docs/seller-central-urls.

**Comment by tusbar** [comment]
@sw-engineer-a thank you for reporting this!
